name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install test and lint tooling
          pip install pytest pytest-asyncio ruff

      - name: Run linters (ruff)
        run: |
          # keep lint step non-blocking for initial PRs
          ruff check . || true

      - name: Run unit tests
        env:
          CI: true
        run: |
          # Run focused unit tests to avoid optional heavy dependencies
          PYTHONPATH=$(pwd) pytest -q tests/test_week4_features.py tests/test_week4_features_extra.py
